version: '3'
# 声明一个名为network的networks,subnet为network的子网地址,默认网关是177.7.0.1
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

services:
  redirect-endpoint:
    build:
      context: ../server
      dockerfile: ./endpoint.Dockerfile
    container_name: redirect-endpoint
    restart: always
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    ports:
      - '80:9091' #跳转物理映射端口号，根据需要进行修改，建议为80
    networks:
      network:
        ipv4_address: 177.7.0.12

  redirect-admin:
    build:
      context: ../server
      dockerfile: ./admin.Dockerfile
    container_name: redirect-admin
    restart: always
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    ports:
      - '9092:9092'
    networks:
      network:
        ipv4_address: 177.7.0.13


  postgres:
    image: postgres:14.7
    container_name: redirect-postgresql
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Td-H7boss:dns
      - TZ=PRC
      - PGTZ=PRC
      - ALLOW_IP_RANGE=0.0.0.0/0
    volumes:
      - ../server/sys_url_redirect.sql:/docker-entrypoint-initdb.d/001.sql
      - ../docker/container-data/postgresql:/var/lib/postgresql/data
    ports:
      - '5342:5342'
    networks:
      network:
        ipv4_address: 177.7.0.14

  redis:
    image: redis:6.2.6
    container_name: redirect-redis
    hostname: redis
    volumes:
      - ../docker/container-data/redis:/data
    ports:
      - '6379:6379'
    command: redis-server --requirepass "Tdun_Rd6666"
    networks:
      network:
        ipv4_address: 177.7.0.15


  redirect-web:
    build:
      context: ../web/admin
      dockerfile: ./Dockerfile
    container_name: redirect-web
    restart: always
    ports:
      - '3002:3002'
    depends_on:
      - redirect-admin
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
      network:
        ipv4_address: 177.7.0.16

  redirect-echart:
    build:
      context: ../web/echart
      dockerfile: ./Dockerfile
    container_name: redirect-echart
    restart: always
    ports:
      - '3003:3003'
    depends_on:
      - redirect-admin
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
      network:
        ipv4_address: 177.7.0.17
